# Generated by Django 5.1.6 on 2025-02-27 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apparatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ex_no", models.CharField(max_length=50)),
                ("course_code", models.CharField(max_length=50)),
                ("practical_course", models.CharField(max_length=255)),
                ("experiment_name", models.CharField(max_length=255)),
                ("regulation", models.CharField(max_length=50)),
                ("batch", models.CharField(max_length=50)),
                ("semester", models.IntegerField()),
                ("apparatus_name", models.CharField(max_length=255)),
                (
                    "range_specification",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("quantity_available", models.CharField(max_length=10)),
                ("department", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "category_table",
            },
        ),
        migrations.CreateModel(
            name="LabExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Ex_no", models.CharField(max_length=50)),
                ("practical_course", models.CharField(max_length=255)),
                ("course_code", models.CharField(max_length=10)),
                ("Ex_title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("regulations", models.CharField(max_length=50)),
                ("batch", models.CharField(max_length=50)),
                ("sem", models.IntegerField()),
                ("department", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="SubjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "subject_type_table",
            },
        ),
        migrations.CreateModel(
            name="LabBatchAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lab_batch_no", models.CharField(max_length=50)),
                ("course_code", models.CharField(max_length=10)),
                ("ex_no", models.CharField(max_length=50)),
                ("assessment", models.CharField(blank=True, max_length=100, null=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("section", models.CharField(blank=True, max_length=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_assignments",
                        to="equipment.student_cgpa",
                    ),
                ),
            ],
            options={
                "db_table": "lab_batch_assignment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApparatusRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[("Request", "Request"), ("Return", "Return")],
                        default="Request",
                        max_length=10,
                    ),
                ),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                            ("Returned", "Returned"),
                            ("Damaged", "Damaged"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("technician_remarks", models.TextField(blank=True, null=True)),
                ("accepted_message", models.TextField(blank=True, null=True)),
                ("return_date", models.DateTimeField(blank=True, null=True)),
                (
                    "fine_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("hod_approval", models.BooleanField(default=False)),
                (
                    "apparatus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipment.apparatus",
                    ),
                ),
                (
                    "damaged_apparatus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="damaged_apparatus",
                        to="equipment.apparatus",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipment.student_cgpa",
                    ),
                ),
                (
                    "technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="equipment.user",
                    ),
                ),
                (
                    "lab_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipment.labbatchassignment",
                    ),
                ),
            ],
            options={
                "db_table": "apparatus_request",
                "ordering": ["-request_date"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch", models.CharField(max_length=50)),
                ("regulations", models.CharField(max_length=20)),
                ("department", models.CharField(max_length=50)),
                ("semester", models.IntegerField()),
                ("course_code", models.CharField(max_length=10, unique=True)),
                ("course_title", models.CharField(max_length=255)),
                ("lecturer", models.IntegerField()),
                ("tutorial", models.IntegerField()),
                ("practical", models.IntegerField()),
                ("total_contact_periods", models.IntegerField()),
                ("credits", models.IntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipment.category",
                    ),
                ),
                (
                    "subject_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipment.subjecttype",
                    ),
                ),
            ],
            options={
                "db_table": "course",
            },
        ),
    ]
