# Generated by Django 5.1.6 on 2025-02-17 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apparatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ex_no", models.CharField(max_length=50)),
                ("course_code", models.CharField(max_length=50)),
                ("practical_course", models.CharField(max_length=255)),
                ("experiment_name", models.CharField(max_length=255)),
                ("regulation", models.CharField(max_length=50)),
                ("batch", models.CharField(max_length=50)),
                ("semester", models.IntegerField()),
                ("apparatus_name", models.CharField(max_length=255)),
                (
                    "range_specification",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("quantity_available", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "category_table",
            },
        ),
        migrations.CreateModel(
            name="LabExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Ex_no", models.CharField(max_length=50, unique=True)),
                ("practical_course", models.CharField(max_length=255)),
                ("course_code", models.CharField(max_length=10)),
                ("Ex_title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("regulations", models.CharField(max_length=50)),
                ("batch", models.CharField(max_length=50)),
                ("sem", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SubjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "subject_type_table",
            },
        ),
        migrations.AlterModelOptions(
            name="student_cgpa",
            options={},
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch", models.CharField(max_length=50)),
                ("regulations", models.CharField(max_length=20)),
                ("degree", models.CharField(max_length=10)),
                ("department", models.CharField(max_length=50)),
                ("semester", models.IntegerField()),
                ("course_code", models.CharField(max_length=10, unique=True)),
                ("course_title", models.CharField(max_length=255)),
                ("lecturer", models.IntegerField()),
                ("tutorial", models.IntegerField()),
                ("practical", models.IntegerField()),
                ("total_contact_periods", models.IntegerField()),
                ("credits", models.IntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipment.category",
                    ),
                ),
                (
                    "subject_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipment.subjecttype",
                    ),
                ),
            ],
            options={
                "db_table": "course",
            },
        ),
    ]
