# Generated by Django 5.1.6 on 2025-02-27 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0002_apparatus_category_labexercise_subjecttype_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="apparatus",
            table="equipment_apparatus",
        ),
    ]
