# Generated by Django 5.1.6 on 2025-02-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0002_apparatus_category_labexercise_subjecttype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_cgpa",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student_cgpa",
            name="section",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
