# Generated by Django 5.1.6 on 2025-02-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0003_alter_apparatus_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="apparatusrequest",
            name="course_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
