# Generated by Django 5.1.6 on 2025-03-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0003_apparatus_experiment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apparatus",
            name="quantity_available",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="apparatus",
            name="range_specification",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
