# Generated by Django 5.1.6 on 2025-02-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0003_student_cgpa_gender_student_cgpa_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="degree1",
            field=models.CharField(default="degree1", max_length=20),
            preserve_default=False,
        ),
    ]
