# Generated by Django 5.1.6 on 2025-02-17 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0004_course_degree1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="degree1",
        ),
    ]
