# Generated by Django 5.1.6 on 2025-03-21 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0004_alter_apparatus_quantity_available_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabBatchMarkEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "technician_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "marks_obtained",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "max_marks",
                    models.DecimalField(decimal_places=2, default=100, max_digits=5),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("entry_date", models.DateTimeField(auto_now_add=True)),
                (
                    "apparatus",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_marks",
                        to="equipment.apparatus",
                    ),
                ),
                (
                    "lab_batch",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks",
                        to="equipment.labbatchassignment",
                    ),
                ),
                (
                    "lab_exercise",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_marks",
                        to="equipment.labexercise",
                    ),
                ),
            ],
            options={
                "db_table": "lab_batch_mark_entry",
                "ordering": ["-entry_date"],
                "unique_together": {("lab_batch", "lab_exercise")},
            },
        ),
    ]
