# Generated by Django 5.1.6 on 2025-02-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0005_remove_apparatusrequest_damaged_apparatus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apparatus",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
