# Generated by Django 5.1.6 on 2025-02-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0005_remove_course_degree1"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student_cgpa",
            options={"managed": True},
        ),
        migrations.AlterField(
            model_name="student_cgpa",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female")],
                default=0,
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student_cgpa",
            name="section",
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
