# Generated by Django 5.1.6 on 2025-03-11 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0006_alter_payment_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="equipment.student_cgpa",
            ),
        ),
    ]
