# Generated by Django 5.1.6 on 2025-02-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0006_apparatus_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="apparatusrequest",
            name="technician_staff_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
