# Generated by Django 5.1.6 on 2025-03-22 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0007_alter_labbatchmarkentry_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="labbatchmarkentry",
            unique_together={("lab_batch", "lab_exercise")},
        ),
        migrations.RemoveField(
            model_name="labbatchmarkentry",
            name="student",
        ),
    ]
