# Generated by Django 5.1.6 on 2025-02-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0007_apparatusrequest_technician_staff_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="apparatusrequest",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="apparatusrequest",
            name="verified_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
