# Generated by Django 5.1.6 on 2025-03-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0008_apparatusrequest_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apparatus",
            name="fine_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
