# Generated by Django 5.1.6 on 2025-03-11 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0008_alter_payment_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="damaged_apparatus",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="lab_batch",
        ),
    ]
