# Generated by Django 5.1.6 on 2025-03-22 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0008_alter_labbatchmarkentry_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="labbatchmarkentry",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="labbatchmarkentry",
            name="student",
            field=models.ForeignKey(
                db_constraint=False,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_marks",
                to="equipment.student",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="labbatchmarkentry",
            unique_together={("student", "lab_batch", "lab_exercise")},
        ),
    ]
