# Generated by Django 5.1.6 on 2025-02-20 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0008_alter_student_cgpa_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student_cgpa",
            options={"managed": False},
        ),
    ]
