# Generated by Django 5.1.6 on 2025-03-11 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0009_remove_payment_damaged_apparatus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labbatchassignment",
            name="student",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lab_assignments",
                to="equipment.student_cgpa",
            ),
        ),
    ]
