# Generated by Django 5.1.6 on 2025-03-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0009_alter_labbatchmarkentry_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="labbatchmarkentry",
            name="is_marked",
            field=models.BooleanField(default=False),
        ),
    ]
