# Generated by Django 5.1.6 on 2025-03-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0010_remove_apparatusrequest_fine_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="regulation_master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("regulation_year", models.IntegerField()),
                ("regulation_name", models.CharField(max_length=100)),
            ],
        ),
    ]
