# Generated by Django 5.1.6 on 2025-02-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0010_alter_labexercise_ex_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="degree",
        ),
    ]
