# Generated by Django 5.1.6 on 2025-03-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0010_alter_labbatchassignment_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
