# Generated by Django 5.1.6 on 2025-02-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0011_remove_course_degree"),
    ]

    operations = [
        migrations.AddField(
            model_name="labexercise",
            name="department",
            field=models.CharField(default="exit", max_length=50),
            preserve_default=False,
        ),
    ]
