# Generated by Django 5.1.6 on 2025-03-07 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0011_regulation_master"),
    ]

    operations = [
        migrations.DeleteModel(
            name="regulation_master",
        ),
    ]
