# Generated by Django 5.1.6 on 2025-02-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0012_labexercise_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="apparatus",
            name="department",
            field=models.CharField(default="exit", max_length=50),
            preserve_default=False,
        ),
    ]
