# Generated by Django 5.1.6 on 2025-03-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0012_delete_regulation_master"),
    ]

    operations = [
        migrations.CreateModel(
            name="regulation_master",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("regulation_year", models.IntegerField()),
                ("regulation_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="apparatusrequest",
            name="fine_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
