# Generated by Django 5.1.6 on 2025-03-11 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "equipment",
            "0012_remove_payment_verified_payment_damaged_apparatus_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="damaged_apparatus",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="lab_batch",
        ),
        migrations.AddField(
            model_name="payment",
            name="damage_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="equipment.apparatusrequestdamage",
            ),
        ),
    ]
