# Generated by Django 5.1.6 on 2025-03-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0013_remove_payment_damaged_apparatus_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="damage_request",
        ),
        migrations.AddField(
            model_name="payment",
            name="damaged_apparatus",
            field=models.ManyToManyField(
                blank=True, to="equipment.apparatusrequestdamage"
            ),
        ),
    ]
