# Generated by Django 5.1.6 on 2025-02-20 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0013_apparatus_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabBatchAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lab_batch_no", models.CharField(max_length=50)),
                ("course_code", models.CharField(max_length=10)),
                ("ex_no", models.CharField(max_length=50)),
                ("assessment", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_assignments",
                        to="equipment.student_cgpa",
                    ),
                ),
            ],
            options={
                "db_table": "lab_batch_assignment",
                "ordering": ["-created_at"],
            },
        ),
    ]
