# Generated by Django 5.1.6 on 2025-02-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0014_labbatchassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="labbatchassignment",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="labbatchassignment",
            name="section",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
