# Generated by Django 5.1.6 on 2025-03-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0014_alter_student_cgpa_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="apparatusrequest",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
