# Generated by Django 5.1.6 on 2025-03-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0016_remove_apparatusrequest_fine_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apparatus",
            name="regulation",
        ),
        migrations.AddField(
            model_name="apparatusrequest",
            name="fine_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="apparatusrequest",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
