# Generated by Django 5.1.6 on 2025-02-22 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0016_labbatchassignment_accepted_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labbatchassignment",
            name="accepted_at",
        ),
        migrations.RemoveField(
            model_name="labbatchassignment",
            name="accepted_by",
        ),
        migrations.RemoveField(
            model_name="labbatchassignment",
            name="apparatus_accepted",
        ),
    ]
