# Generated by Django 5.1.6 on 2025-03-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0017_remove_apparatus_regulation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apparatus",
            name="fine_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
