# Generated by Django 5.1.6 on 2025-03-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0019_apparatus_regulation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apparatus",
            name="regulation",
        ),
    ]
