# Generated by Django 5.1.6 on 2025-03-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0020_remove_apparatus_regulation"),
    ]

    operations = [
        migrations.AddField(
            model_name="apparatus",
            name="regulation",
            field=models.CharField(default="Default Regulation", max_length=50),
            preserve_default=False,
        ),
    ]
