# Generated by Django 5.1.6 on 2025-03-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0021_apparatus_regulation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apparatusrequest",
            name="remarks",
        ),
        migrations.AlterField(
            model_name="apparatus",
            name="fine_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
