# Generated by Django 5.1.6 on 2025-03-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0022_remove_apparatusrequest_remarks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apparatusrequest",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
