# Generated by Django 5.1.6 on 2025-03-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0023_apparatusrequest_remarks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apparatus",
            old_name="regulation",
            new_name="regulations",
        ),
    ]
