# Generated by Django 5.1.6 on 2025-03-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0024_rename_regulation_apparatus_regulations"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apparatus",
            old_name="regulations",
            new_name="regulation",
        ),
    ]
