# Generated by Django 5.1.6 on 2025-03-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0026_payment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student_cgpa",
            options={"managed": False},
        ),
    ]
